### ISSUE TITLE
Doesn’t launch

### ISSUE THREAD

**Issue by jnoxon** [benbrackenbury/SpaceX-Explorer#1]
Hey, I just noticed the app lives here, so I'll go delete my App Store review. It used to crash on iOS 14 at launch. The current App Store release launches to a black screen. I'm not sure how to help troubleshoot this, but I'm game to try. I have Xcode and a developer account, although I haven't done any iOS app development in over five years. Should I try to build it and install it? Or is there a TestFlight? Please let me know how I can help.

**Comment by benbrackenbury** [comment]
Hi Jeff,

I'm really sorry that you're experiencing issues with the app.

There is a [TestFlight available here](https://testflight.apple.com/join/oxiMqcAw); I'll have a look into the issue this week and  push updates to the TF for you to try.

I have also created a [copy of the Xcode project](https://envl.app/benbrackenbury/KRd20t!7QjyYyGuXvIsElU1) if you'd like to try compiling & running yourself.

Once again I would like to apologise for the issue, as well as saying thank you for taking the time to let me know and for helping to fix the app.

**Comment by jnoxon** [comment]
No worries! And thanks!

I downloaded the project and it built and runs great in the simulator. I'm currently going through the usual headaches trying to get it work on-device.

**Comment by jnoxon** [comment]
Ugh, I figured out what I was doing wrong with xcode and got the build on my phone and ... it works. So I'm afraid I have no idea how to troubleshoot the app store version any further.

**Comment by jnoxon** [comment]
Oh, I feel like an idiot. And I have a lead for you.

When the old app didn't run on iOS 14, I removed it and re-installed it, because that sometimes works for apps that have bad caches or whatnot. The app still didn't run, so I didn't think about trying that again.

But it turns out that deleting the app and reinstalling did solve the problem, when I tried it again just now with 2.0.

**Comment by benbrackenbury** [comment]
Haha the classic solution. Thanks so much for trying all of this, I appreciate it a lot!
